accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectCreateView,
    ProjectListView,
    ProjectDetailView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import TaskCompletionUpdateView, TaskCreateView, SelfTaskListView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path(
        "<int:pk>/complete/",
        TaskCompletionUpdateView.as_view(),
        name="complete_task",
    ),
    path("mine/", SelfTaskListView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}

    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import redirect

from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_query(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_query(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        project = form.save(commit=True)
        return redirect("show_project", pk=project.id)

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from tasks.models import Task

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


# def form_valid(self, form):
#     form.save()
#     return redirect("list_projects")


class SelfTaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/my_tasks.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskCompletionUpdateView(UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="A website to track your projects"/>
        <meta name="keywords" content="project"/>
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Create a New Project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends "base.html" %}
{% load markdownify %}
{% block content %}
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <p>
                <a href="{% url "create_task" %}">Create A New Task</a>
            </p>
            <table>
                {% if not project.tasks.all %}
                    <p>This project has no tasks</p>
                {% else %}
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed|yesno:"Yes,No" }}</td>
                            </tr>
                        {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <div>
                <a href="{% url "create_project" %}">Create a new project</a>
            </div>
            {% if not user.projects.all %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>
                                    <a href="{% url "show_project" project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>Create a New Task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/my_tasks.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if not user.tasks.all %}<p>You have no tasks</p>{% endif %}
            {% if user.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                        <tbody>
                            {% for task in user.tasks.all %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>
                                        {{ task.is_completed|yesno:"Done," }}
                                        {% if task.is_completed == False %}
                                            <form method="post" action="{% url 'complete_task' task.id %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="is_completed" value="True"/>
                                                <button>Complete</button>
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </thead>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}